name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the artifact to deploy
        required: true
        default: 'artifact'
        type: string
    outputs:
      result:
        description: The result of the deploy operation
        value: ${{ jobs.deploy.outputs.outcome}}

    secrets:
      some-secret:
        description: 'A secret to use in the workflow'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
      
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          
      - name: Output Information
        run: echo "Deploy & Upload"

      - name: Set result output
        id: set-result
        run: echo "echo "step-result=success" >> $GITHUB_OUTPUT"